version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - esnet
    depends_on:
      - elasticsearch

  loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tmdb-loader
    environment:
      - TMDB_API_KEY=your_tmdb_key_here
      - ELASTIC_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - esnet
    restart: "no"

networks:
  esnet:
    driver: bridge
